name: hhpinn
channels:
  - defaults
dependencies:
  - python=3.9
  - numpy
  - scipy
  - matplotlib
  - jupyterlab
  - ipython
  - pandas
  - scikit-learn
  - pytest
  - pip
  - pip:
    - tensorflow=2.7
